# Generated by Django 4.2.5 on 2023-09-25 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonstatus",
            name="watched_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
