# Generated by Django 4.2.5 on 2023-09-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0002_lessonstatus_watched_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonstatus",
            name="watched_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
